Areas/Community/Controllers/ViewUserController.cs
using System.Data.Entity;
using App.Areas.Community.Models;
using App.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Org.BouncyCastle.Bcpg;


namespace App.Areas.Community.Controllers
{
    [Area("Community")]
    [Authorize]
    public class ViewUserController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public ViewUserController (AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [Route("viewuser/profile/{name}")]
        public async Task<ActionResult> Index(string name)
        {
            var user = await _userManager.FindByNameAsync(name);
            if(user == null)
                return Content("Not found user!");

            ViewUserModel viewUser = new ViewUserModel()
            {
                UserId = user.Id,
                UserName = user.UserName,
                UserEmail = user.Email,
                PhoneNumber = user.PhoneNumber,
                HomeAdress = user.HomeAddress,
                BirthDate = user.BirthDate,
                AvatarUser = _context.UserAvatars.Where(a => a.UserID == user.Id).FirstOrDefault()
            };
            return View(viewUser);
        }

        [Route("viewuser/users")]
        public ActionResult ViewAllUsers()
        {
            var currUserId = _userManager.GetUserId(User);
            var users = _context.Users.Select(user => new {
                Id = user.Id,
                UserName = user.UserName,
                AvatarName = _context.UserAvatars.Where(a => a.UserID == user.Id).FirstOrDefault().AvatarName,
            }).ToList();

            var result = users.Find(u => u.Id == currUserId);
            if(result != null) users.Remove(result);
            
            ViewBag.users = users;
            return View();
        }
    }
}

Areas/Community/Views/ViewUser/Index.cshtml
@using App.Areas.Community.Models;

@model ViewUserModel

@{
    ViewData["Title"] = "Thông tin người dùng";
    var srcImg = "";
}

<h1>@ViewData["Title"] @Model.UserName.</h1>

<form asp-controller="ChatUser" asp-action="Index" asp-area="Community" hidden="true">
   <div class="form-group">
      <input asp-for="UserId" class="form-control"/>
   </div>
   <input id="submit-chat" type="submit"/>
</form>
<a id="btn-chat-user" onclick="document.getElementById(`submit-chat`).click()" class=" btn btn-outline-secondary">
   <i class="far fa-comment-dots"></i> Chat</a>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-4">Avatar:</dt>
        <dd class="col-sm-6">
            @if (Model.AvatarUser == null)
                srcImg = "/contents/noUser.png";
            else
                srcImg = "/contents/AvatarUsers/" + Model.AvatarUser.AvatarName;
            
            <img src=@srcImg class="w-25" alt="...">
        </dd>

        <dt class="col-sm-4">Thông tin cơ bản:</dt>
        <dd class="col-sm-6"> 
            <dl class="row">
                 <dt class = "col-sm-6">
                    @Html.DisplayNameFor(m => Model.UserName)
                 </dt>   
                 <dd class = "col-sm-6">
                    @Html.DisplayFor(m => Model.UserName)
                 </dd>
            </dl>
             <dl class="row">
                 <dt class = "col-sm-6">
                    @Html.DisplayNameFor(m => Model.UserEmail)
                 </dt>   
                 <dd class = "col-sm-6">
                    @Html.DisplayFor(m => Model.UserEmail)
                 </dd>
            </dl>
              <dl class="row">
                 <dt class = "col-sm-6">
                    @Html.DisplayNameFor(m => Model.PhoneNumber)
                 </dt>   
                 <dd class = "col-sm-6">
                    @Html.DisplayFor(m => Model.PhoneNumber)
                 </dd>
            </dl>
               <dl class="row">
                 <dt class = "col-sm-6">
                    @Html.DisplayNameFor(m => Model.HomeAdress)
                 </dt>   
                 <dd class = "col-sm-6">
                    @Html.DisplayFor(m => Model.HomeAdress)
                 </dd>
            </dl>                   
                <dl class="row">
                 <dt class = "col-sm-6">
                    @Html.DisplayNameFor(m => Model.BirthDate)
                 </dt>   
                 <dd class = "col-sm-6">
                    @Html.DisplayFor(m => Model.BirthDate)
                 </dd>
            </dl>      
        </dd>
    </dl>
</div>

@section Scripts{
   <script>
      fetch("/api/get-current-user-login", {method: "GET"})
      .then(response => response.json())
      .then(data => {
         if(data.success === true){
            if("@Model.UserId" == data.id){
               document.getElementById("btn-chat-user").hidden = true;
            }
            else{
               document.getElementById("btn-chat-user").hidden = false;
            }
         }
      })
      .catch(error => console.error(error));
   </script>
}

Areas/Community/Views/ViewUser/ViewAllUsers.cshtml
@using App.Areas.Community.Models;

@model ViewUserModel
@{
    ViewData["Title"] = "People";
    var users = ViewBag.users;
}

<style>
    .avatar-user{
        max-height: 50px;
        max-width: 70px;
        margin-top: 5px;
    }
    .card{
        margin-right: 8px;
        margin-bottom: 8px;
        height: 250px;
    }
</style>

<h1>@ViewData["Title"]</h1> <br> <br>

<div id="card-product" class="d-flex flex-wrap justify-content-center">
    @foreach(var user in users)
    {
        var srcImg = "";
        @if(user.AvatarName == null)
            srcImg = "/contents/noUser.png";
        else
            srcImg = "/contents/AvatarUsers/" + user.AvatarName;
        
        <form asp-controller="ChatUser" asp-action="Index" asp-area="Community" class="card text-center border-info" style="width: 15rem;">
            <div>
                <img class="avatar-user card-img-top" src=@srcImg alt="...">
            </div>
            <div class="card-body">
                <h5 class=" card-title">@user.UserName</h5>
                <p id="status-@user.UserName" class="card-text"> 
                    <i style="color: red;" class="fas fa-dot-circle"></i>
                    <span>Offline</span>
                </p>
                <div class="" hidden="true">
                    <input asp-for="UserId" value="@user.Id" class="form-control"/>
                </div> 
            </div>
            <div class="card-footer">
                <button id="submit-chat" class="btn btn-outline-secondary" type="submit"><i class="far fa-comment-dots"></i> Chat</button>
                <button class="btn btn-outline-primary" asp-area="Community" 
                    asp-controller="ViewUser" asp-action="Index" 
                    asp-route-name="@user.UserName">View Profile
                </button>
            </div>
        </form>
    }
</div>

@section Scripts{
    <script>
        var timer;
        function UpdateStatusUserViewAllUser()
        {
            fetch("/api/get-user-connect-chat", {method: "POST"})
            .then(response => response.json())
            .then(function (data){
                for(let i = 0; i < data.listOff.length; i++){
                    document.getElementById(`status-${data.listOff[i].userName}`).firstElementChild.style.color = "red";
                    document.getElementById(`status-${data.listOff[i].userName}`).lastElementChild.textContent = "Offline";
                }
                
                for(let i = 0; i < data.listOnl.length; i++){
                    document.getElementById(`status-${data.listOnl[i].userName}`).firstElementChild.style.color = "green";
                    document.getElementById(`status-${data.listOnl[i].userName}`).lastElementChild.textContent = "Online";

                }
            })
            .catch(error => console.error(error));
        }

        function ReloadViewUser()
        {
            timer = setTimeout(() => {
                UpdateStatusUserViewAllUser();
                ReloadViewUser();
            }, 10000);
        }

        UpdateStatusUserViewAllUser();
        ReloadViewUser();
    </script>
}